---
- name: Clonando template do operator
  ansible.builtin.git: 
    repo: "https://github.com/ansible-consulting-br/helm-operator.git"
    dest: "/tmp/helm-operator/"
    single_branch: yes
    version: main

- name: Verificando se o repositório foi clonado com sucesso
  ansible.builtin.stat:
    path: "/tmp/helm-operator/"
  register: directory_info

- name: Debug
  debug:
    var: directory_info
  when: debug_enabled
  
- name: Gerando template do operator
  kubernetes.core.helm_template:
    output_dir: "/tmp/helm-output/"
    chart_ref: "/tmp/helm-operator/"
    values: 
      name: "{{ operator_name }}"
      namespace: "{{ operator_namespace }}"
      subscription:
        channel: "{{ subscription_channel }}"
        installPlanApproval: "{{ subscription_plan_approval }}"
        source:  "{{ subscription_source }}"
        sourceNamespace: "{{ subscription_source_namespace }}"
  register: result
  when: directory_info.stat.exists

- name: Verificando se o repositório de saída foi criado com sucesso
  ansible.builtin.stat:
    path: "/tmp/helm-operator-output/"
  register: directory_info_output

# - name: Debug
#   debug:
#     var: result.stdout
#   when: debug_enabled
#
# - name: Escreve os templates em arquivo
#   ansible.builtin.copy:
#     dest: /tmp/operator.yaml
#     content: "{{ result.stdout }}"

- name: Aplica recursos no Openshift
  kubernetes.core.k8s:
    definition: "{{ lookup('file', '{{ item }}') | from_yaml }}"
  with_fileglob:
    - "/tmp/helm-output/operator/templates/*.yaml"
    - "/tmp/helm-output/operator/templates/*.yml"