---
- name: Clonando template do operator
  ansible.builtin.git: 
    repo: "{{ core_install_git_url }}"
    dest: "{{ core_install_git_dest }}"
    single_branch: yes
    version: main

- name: Verificando se o repositório foi clonado com sucesso
  ansible.builtin.stat:
    path: "{{ core_install_git_dest }}"
  register: directory_info

- name: Debug
  debug:
    var: directory_info
  when: debug_enabled
  
- name: Gerando template do operator
  kubernetes.core.helm_template:
    output_dir: "{{ core_install_folder }}"
    chart_ref: "{{ core_install_git_dest }}"
    set_values: "{{ core_install_helm_set_values }}"
    values_files: "{{ core_install_helm_values }}"
    values: 
      name: "{{ operator_name }}"
      namespace: "{{ operator_namespace }}"
      subscription:
        channel: "{{ subscription_channel }}"
        installPlanApproval: "{{ subscription_plan_approval }}"
        source:  "{{ subscription_source }}"
        sourceNamespace: "{{ subscription_source_namespace }}"
  register: result
  when: directory_info.stat.exists

- name: Verificando se o repositório de saída foi criado com sucesso
  ansible.builtin.stat:
    path: "{{ core_install_folder }}"
  register: directory_info_output

# - name: Debug
#   debug:
#     var: result.stdout
#   when: debug_enabled
#
# - name: Escreve os templates em arquivo
#   ansible.builtin.copy:
#     dest: /tmp/operator.yaml
#     content: "{{ result.stdout }}"

- name: Aplica recursos no Openshift
  kubernetes.core.k8s:
    namespace: "{{ core_install_namespace }}"
    definition: "{{ lookup('file', '{{ item }}') | from_yaml }}"
  with_fileglob:
    - "{{ core_install_folder }}{{ core_install_folder_subpath }}/*.yml"
    - "{{ core_install_folder }}/{{ core_install_folder_subpath }}/*.yaml"