---
- name: "Operator :: Instala Operator"
  include_role:
    name: ocp-core

- name: "Operator :: Aguarda Subscription"
  kubernetes.core.k8s_info:
    api_version: operators.coreos.com/v1alpha1
    kind: Subscription
    name: "{{ operator_install_name }}"
    namespace: "{{ operator_install_namespace }}"
    wait: yes
    wait_sleep: 20
    wait_timeout: 360
    wait_condition:
      type: CatalogSourcesUnhealthy
      status: 'False'
      reason: AllCatalogSourcesHealthy
  register: operator_info