---
- name: Clonando template do operator
  ansible.builtin.git: 
    repo: "https://github.com/ansible-consulting-br/helm-operator.git"
    dest: "/tmp/helm-operator/"
    single_branch: yes
    version: main

- name: Verificando se o repositório foi clonado com sucesso
  ansible.builtin.stat:
    path: "/tmp/helm-operator/"
  register: directory_info

#- name: Debug
#  debug:
#    var: directory_info
  
- name: Gerando template do operator
  kubernetes.core.helm_template:
    output_dir: "/tmp/helm-operator-output/"
    chart_ref: "/tmp/helm-operator/"
    values: 
      name: "{{ operator_name }}"
      namespace: "{{ operator_namespace }}"
      subscription:
        channel: "{{ subscription_channel }}"
        installPlanApproval: "{{ subscription_plan_approval }}"
        source:  "{{ subscription_source }}"
        sourceNamespace: "{{ subscription_source_namespace }}"
  when: directory_info.stat.exists

- name: Verificando se o repositório de saída foi criado com sucesso
  ansible.builtin.stat:
    path: "/tmp/helm-operator-output/"
  register: directory_info_output

#- name: Debug
#  debug:
#    var: directory_info_output